pipeline:
  build:
    image: alpine:3.4
    commands:
      - env

  build_docker_image:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t quay.io/molleen/test:${DRONE_COMMIT_SHA} .

  image_to_quay:
    image: docker:1.11
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="molleen+molleen_write" -p=${DOCKER_PASSWORD} quay.io
      - docker push quay.io/molleen/test:${DRONE_COMMIT_SHA}
      # - mkdir /root/.docker
      # - sh -c 'echo ${DOCKER_LOGIN} | base64 -d > /root/.docker/config.json'
      # - docker tag brpapp quay.io/ukhomeofficedigital/brpapp-test:${DRONE_COMMIT_SHA}
      # - docker push quay.io/ukhomeofficedigital/brpapp-test:${DRONE_COMMIT_SHA}


services:
  dind:
    image: docker:1.11-dind
    privileged: true
